/*
Femsa API

Testing ProductsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package digitalfemsa

import (
	"context"
	openapiclient "github.com/digitalfemsa/digitalfemsa-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_digitalfemsa_ProductsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ProductsAPIService OrdersCreateProduct", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var id string

		resp, httpRes, err := apiClient.ProductsAPI.OrdersCreateProduct(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProductsAPIService OrdersDeleteProduct", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var id string
		var lineItemId string

		resp, httpRes, err := apiClient.ProductsAPI.OrdersDeleteProduct(context.Background(), id, lineItemId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProductsAPIService OrdersUpdateProduct", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var id string
		var lineItemId string

		resp, httpRes, err := apiClient.ProductsAPI.OrdersUpdateProduct(context.Background(), id, lineItemId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
