/*
Femsa API

Femsa sdk

API version: 2.1.0
Contact: engineering@femsa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digitalfemsa

import (
	"encoding/json"
)

// checks if the OrderNextActionResponseRedirectToUrl type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderNextActionResponseRedirectToUrl{}

// OrderNextActionResponseRedirectToUrl contains the following attributes that will guide to continue the flow
type OrderNextActionResponseRedirectToUrl struct {
	// pay.femsa.com/{id} Indicates the url of the Femsa component to authenticate the flow through 3DS2.
	Url *string `json:"url,omitempty"`
	// Indicates the url to which the 3DS2 flow returns at the end, when the integration is redirected.
	ReturnUrl            *string `json:"return_url,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OrderNextActionResponseRedirectToUrl OrderNextActionResponseRedirectToUrl

// NewOrderNextActionResponseRedirectToUrl instantiates a new OrderNextActionResponseRedirectToUrl object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderNextActionResponseRedirectToUrl() *OrderNextActionResponseRedirectToUrl {
	this := OrderNextActionResponseRedirectToUrl{}
	return &this
}

// NewOrderNextActionResponseRedirectToUrlWithDefaults instantiates a new OrderNextActionResponseRedirectToUrl object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderNextActionResponseRedirectToUrlWithDefaults() *OrderNextActionResponseRedirectToUrl {
	this := OrderNextActionResponseRedirectToUrl{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *OrderNextActionResponseRedirectToUrl) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderNextActionResponseRedirectToUrl) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *OrderNextActionResponseRedirectToUrl) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *OrderNextActionResponseRedirectToUrl) SetUrl(v string) {
	o.Url = &v
}

// GetReturnUrl returns the ReturnUrl field value if set, zero value otherwise.
func (o *OrderNextActionResponseRedirectToUrl) GetReturnUrl() string {
	if o == nil || IsNil(o.ReturnUrl) {
		var ret string
		return ret
	}
	return *o.ReturnUrl
}

// GetReturnUrlOk returns a tuple with the ReturnUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderNextActionResponseRedirectToUrl) GetReturnUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ReturnUrl) {
		return nil, false
	}
	return o.ReturnUrl, true
}

// HasReturnUrl returns a boolean if a field has been set.
func (o *OrderNextActionResponseRedirectToUrl) HasReturnUrl() bool {
	if o != nil && !IsNil(o.ReturnUrl) {
		return true
	}

	return false
}

// SetReturnUrl gets a reference to the given string and assigns it to the ReturnUrl field.
func (o *OrderNextActionResponseRedirectToUrl) SetReturnUrl(v string) {
	o.ReturnUrl = &v
}

func (o OrderNextActionResponseRedirectToUrl) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderNextActionResponseRedirectToUrl) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.ReturnUrl) {
		toSerialize["return_url"] = o.ReturnUrl
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OrderNextActionResponseRedirectToUrl) UnmarshalJSON(data []byte) (err error) {
	varOrderNextActionResponseRedirectToUrl := _OrderNextActionResponseRedirectToUrl{}

	err = json.Unmarshal(data, &varOrderNextActionResponseRedirectToUrl)

	if err != nil {
		return err
	}

	*o = OrderNextActionResponseRedirectToUrl(varOrderNextActionResponseRedirectToUrl)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "url")
		delete(additionalProperties, "return_url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOrderNextActionResponseRedirectToUrl struct {
	value *OrderNextActionResponseRedirectToUrl
	isSet bool
}

func (v NullableOrderNextActionResponseRedirectToUrl) Get() *OrderNextActionResponseRedirectToUrl {
	return v.value
}

func (v *NullableOrderNextActionResponseRedirectToUrl) Set(val *OrderNextActionResponseRedirectToUrl) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderNextActionResponseRedirectToUrl) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderNextActionResponseRedirectToUrl) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderNextActionResponseRedirectToUrl(val *OrderNextActionResponseRedirectToUrl) *NullableOrderNextActionResponseRedirectToUrl {
	return &NullableOrderNextActionResponseRedirectToUrl{value: val, isSet: true}
}

func (v NullableOrderNextActionResponseRedirectToUrl) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderNextActionResponseRedirectToUrl) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
